/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.ActiveEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionEvent;

/**
 *
 * @author Gercray
 */
public class Monitoreo extends javax.swing.JFrame {

    /**
     * Creates new form Monitoreo
     */
    public Monitoreo() {
        initComponents();
        setLocationRelativeTo(null);
        reloj();
    }
    
    private void reloj() {
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        String horaActual = formatoHora.format(new Date());
        labelReloj.setText(horaActual);
        
        Timer timer = new Timer(1000, (ActionEvent e) -> {
        String hora = formatoHora.format(new Date());
        labelReloj.setText(hora);
        
    });
    timer.start();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btZonas = new javax.swing.JPanel();
        Zona = new javax.swing.JLabel();
        btAnimales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelReloj = new javax.swing.JLabel();
        btAnimales1 = new javax.swing.JPanel();
        btRegistroA = new javax.swing.JLabel();
        btAnimales2 = new javax.swing.JPanel();
        btRegistroZ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Monitoreo logo (2).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MONITOREO DEL SANTUARIO");

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btZonas.setBackground(new java.awt.Color(0, 0, 0));
        btZonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btZonasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btZonasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btZonasMouseExited(evt);
            }
        });

        Zona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Zona.setForeground(new java.awt.Color(255, 255, 255));
        Zona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ZonaMonitoreo (2).jpg"))); // NOI18N
        Zona.setText("MONITOREO DE ZONAS");

        javax.swing.GroupLayout btZonasLayout = new javax.swing.GroupLayout(btZonas);
        btZonas.setLayout(btZonasLayout);
        btZonasLayout.setHorizontalGroup(
            btZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btZonasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Zona, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btZonasLayout.setVerticalGroup(
            btZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btZonasLayout.createSequentialGroup()
                .addComponent(Zona)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btAnimales.setBackground(new java.awt.Color(0, 0, 0));
        btAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnimalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAnimalesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro todo.jpg"))); // NOI18N
        jLabel6.setText("MONITOREO DE ANIMALES");

        javax.swing.GroupLayout btAnimalesLayout = new javax.swing.GroupLayout(btAnimales);
        btAnimales.setLayout(btAnimalesLayout);
        btAnimalesLayout.setHorizontalGroup(
            btAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAnimalesLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        btAnimalesLayout.setVerticalGroup(
            btAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btAnimalesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        labelReloj.setBackground(new java.awt.Color(255, 255, 255));
        labelReloj.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        labelReloj.setForeground(new java.awt.Color(255, 255, 255));
        labelReloj.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1401, Short.MAX_VALUE)
                .addComponent(labelReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReloj)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btAnimales1.setBackground(new java.awt.Color(0, 0, 0));
        btAnimales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnimales1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAnimales1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAnimales1MouseExited(evt);
            }
        });

        btRegistroA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRegistroA.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro Animal (2).jpg"))); // NOI18N
        btRegistroA.setText("VER REGISTRO DE ANIMALES");
        btRegistroA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btRegistroAMouseMoved(evt);
            }
        });
        btRegistroA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistroAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegistroAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegistroAMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btAnimales1Layout = new javax.swing.GroupLayout(btAnimales1);
        btAnimales1.setLayout(btAnimales1Layout);
        btAnimales1Layout.setHorizontalGroup(
            btAnimales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAnimales1Layout.createSequentialGroup()
                .addComponent(btRegistroA, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        btAnimales1Layout.setVerticalGroup(
            btAnimales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btAnimales1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btRegistroA)
                .addContainerGap())
        );

        btAnimales2.setBackground(new java.awt.Color(0, 0, 0));
        btAnimales2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnimales2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAnimales2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAnimales2MouseExited(evt);
            }
        });

        btRegistroZ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRegistroZ.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro Zonas (2).png"))); // NOI18N
        btRegistroZ.setText("VER REGISTRO DE ZONAS");
        btRegistroZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistroZMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegistroZMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegistroZMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btAnimales2Layout = new javax.swing.GroupLayout(btAnimales2);
        btAnimales2.setLayout(btAnimales2Layout);
        btAnimales2Layout.setHorizontalGroup(
            btAnimales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAnimales2Layout.createSequentialGroup()
                .addComponent(btRegistroZ, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        btAnimales2Layout.setVerticalGroup(
            btAnimales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btAnimales2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegistroZ)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAnimales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAnimales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAnimales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btAnimales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79)
                            .addComponent(btZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btZonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseClicked
        // TODO add your handling code here:
        //btnVigilancia.setFocusable(false);
        new GestionVigilantes().setVisible(true);
        dispose();

    }//GEN-LAST:event_btZonasMouseClicked

    private void btZonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseEntered
        // TODO add your handling code here:
        btZonas.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btZonasMouseEntered

    private void btZonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseExited
        // TODO add your handling code here:
        btZonas.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btZonasMouseExited

    private void btAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseClicked
        // TODO add your handling code here:
        //btnAnimales.setFocusable(false);
        new GestionAnimal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btAnimalesMouseClicked

    private void btAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseEntered
        // TODO add your handling code here:
        btAnimales.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btAnimalesMouseEntered

    private void btAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseExited
        // TODO add your handling code here:
        btAnimales.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btAnimalesMouseExited

    private void btAnimales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales1MouseClicked

    private void btAnimales1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales1MouseEntered

    private void btAnimales1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales1MouseExited

    private void btAnimales2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales2MouseClicked

    private void btAnimales2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales2MouseEntered

    private void btAnimales2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimales2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnimales2MouseExited

    private void btRegistroAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroAMouseClicked
        new MonitoreoAnimales().setVisible(true);
        dispose();
    }//GEN-LAST:event_btRegistroAMouseClicked

    private void btRegistroAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroAMouseEntered
        btRegistroA.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btRegistroAMouseEntered

    private void btRegistroAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroAMouseExited
        btRegistroA.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btRegistroAMouseExited

    private void btRegistroAMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroAMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistroAMouseMoved

    private void btRegistroZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroZMouseClicked
        new GestionAnimal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btRegistroZMouseClicked

    private void btRegistroZMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroZMouseEntered
        btRegistroA.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btRegistroZMouseEntered

    private void btRegistroZMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroZMouseExited
        btRegistroA.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btRegistroZMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Zona;
    private javax.swing.JPanel btAnimales;
    private javax.swing.JPanel btAnimales1;
    private javax.swing.JPanel btAnimales2;
    private javax.swing.JLabel btRegistroA;
    private javax.swing.JLabel btRegistroZ;
    private javax.swing.JPanel btZonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelReloj;
    // End of variables declaration//GEN-END:variables
}
