/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.ActiveEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionEvent;

/**
 *
 * @author Gercray
 */
public class Monitoreo extends javax.swing.JFrame {

    /**
     * Creates new form Monitoreo
     */
    public Monitoreo() {
        initComponents();
        setLocationRelativeTo(null);
        reloj();
    }
    
    private void reloj() {
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        String horaActual = formatoHora.format(new Date());
        labelReloj.setText(horaActual);
        
        Timer timer = new Timer(1000, (ActionEvent e) -> {
        String hora = formatoHora.format(new Date());
        labelReloj.setText(hora);
        
    });
    timer.start();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btZonas = new javax.swing.JPanel();
        Zona = new javax.swing.JLabel();
        btAnimales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelReloj = new javax.swing.JLabel();
        VerRegistroA = new javax.swing.JPanel();
        btRegistroA = new javax.swing.JLabel();
        VerRegistroZ = new javax.swing.JPanel();
        btRegistroZ = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Monitoreo logo (2).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MONITOREO DEL SANTUARIO");

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btZonas.setBackground(new java.awt.Color(0, 0, 0));
        btZonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btZonasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btZonasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btZonasMouseExited(evt);
            }
        });

        Zona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Zona.setForeground(new java.awt.Color(255, 255, 255));
        Zona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ZonaMonitoreo (2).jpg"))); // NOI18N
        Zona.setText("MONITOREO DE ZONAS");

        javax.swing.GroupLayout btZonasLayout = new javax.swing.GroupLayout(btZonas);
        btZonas.setLayout(btZonasLayout);
        btZonasLayout.setHorizontalGroup(
            btZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btZonasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Zona, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btZonasLayout.setVerticalGroup(
            btZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btZonasLayout.createSequentialGroup()
                .addComponent(Zona)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btAnimales.setBackground(new java.awt.Color(0, 0, 0));
        btAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnimalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAnimalesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro todo.jpg"))); // NOI18N
        jLabel6.setText("MONITOREO DE ANIMALES");

        javax.swing.GroupLayout btAnimalesLayout = new javax.swing.GroupLayout(btAnimales);
        btAnimales.setLayout(btAnimalesLayout);
        btAnimalesLayout.setHorizontalGroup(
            btAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAnimalesLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        btAnimalesLayout.setVerticalGroup(
            btAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btAnimalesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        labelReloj.setBackground(new java.awt.Color(255, 255, 255));
        labelReloj.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        labelReloj.setForeground(new java.awt.Color(255, 255, 255));
        labelReloj.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1401, Short.MAX_VALUE)
                .addComponent(labelReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReloj)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        VerRegistroA.setBackground(new java.awt.Color(0, 0, 0));
        VerRegistroA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerRegistroAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerRegistroAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerRegistroAMouseExited(evt);
            }
        });

        btRegistroA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRegistroA.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro Animal (2).jpg"))); // NOI18N
        btRegistroA.setText("VER REGISTRO DE ANIMALES");

        javax.swing.GroupLayout VerRegistroALayout = new javax.swing.GroupLayout(VerRegistroA);
        VerRegistroA.setLayout(VerRegistroALayout);
        VerRegistroALayout.setHorizontalGroup(
            VerRegistroALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerRegistroALayout.createSequentialGroup()
                .addComponent(btRegistroA, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        VerRegistroALayout.setVerticalGroup(
            VerRegistroALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerRegistroALayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btRegistroA)
                .addContainerGap())
        );

        VerRegistroZ.setBackground(new java.awt.Color(0, 0, 0));
        VerRegistroZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerRegistroZMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerRegistroZMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerRegistroZMouseExited(evt);
            }
        });

        btRegistroZ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRegistroZ.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registro Zonas (2).png"))); // NOI18N
        btRegistroZ.setText("VER REGISTRO DE ZONAS");

        javax.swing.GroupLayout VerRegistroZLayout = new javax.swing.GroupLayout(VerRegistroZ);
        VerRegistroZ.setLayout(VerRegistroZLayout);
        VerRegistroZLayout.setHorizontalGroup(
            VerRegistroZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerRegistroZLayout.createSequentialGroup()
                .addComponent(btRegistroZ, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        VerRegistroZLayout.setVerticalGroup(
            VerRegistroZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerRegistroZLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegistroZ)
                .addContainerGap())
        );

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BOTON_REGRESAR (1) (1).png"))); // NOI18N
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VerRegistroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VerRegistroZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonRegresar)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(botonRegresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VerRegistroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addComponent(btZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VerRegistroZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btZonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseClicked
        new MonitoreoZonas().setVisible(true);
        dispose();

    }//GEN-LAST:event_btZonasMouseClicked

    private void btZonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseEntered
        btZonas.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btZonasMouseEntered

    private void btZonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btZonasMouseExited
        btZonas.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btZonasMouseExited

    private void btAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseClicked
        new MonitoreoAnimales().setVisible(true);
        dispose();
    }//GEN-LAST:event_btAnimalesMouseClicked

    private void btAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseEntered
        btAnimales.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_btAnimalesMouseEntered

    private void btAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnimalesMouseExited
        btAnimales.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btAnimalesMouseExited

    private void VerRegistroAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroAMouseClicked
        new RegistroAnimales().setVisible(true);
        dispose();
    }//GEN-LAST:event_VerRegistroAMouseClicked

    private void VerRegistroAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroAMouseEntered
        VerRegistroA.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_VerRegistroAMouseEntered

    private void VerRegistroAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroAMouseExited
        VerRegistroA.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_VerRegistroAMouseExited

    private void VerRegistroZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroZMouseClicked
        new RegistroZonas().setVisible(true);
        dispose();
    }//GEN-LAST:event_VerRegistroZMouseClicked

    private void VerRegistroZMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroZMouseEntered
        VerRegistroZ.setBackground(new java.awt.Color(0, 51, 153));
    }//GEN-LAST:event_VerRegistroZMouseEntered

    private void VerRegistroZMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerRegistroZMouseExited
        VerRegistroZ.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_VerRegistroZMouseExited

    private void botonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseClicked
        new Administrador().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VerRegistroA;
    private javax.swing.JPanel VerRegistroZ;
    private javax.swing.JLabel Zona;
    private javax.swing.JLabel botonRegresar;
    private javax.swing.JPanel btAnimales;
    private javax.swing.JLabel btRegistroA;
    private javax.swing.JLabel btRegistroZ;
    private javax.swing.JPanel btZonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelReloj;
    // End of variables declaration//GEN-END:variables
}
